{
	"version": 1648053090,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/button-sheet0.png",
		"images/map-sheet0.png",
		"images/enemy-sheet0.png",
		"images/hp-sheet0.png",
		"images/mana-sheet0.png",
		"images/back-sheet0.png",
		"images/fight-sheet0.png",
		"images/map2-sheet0.png",
		"images/Спрайт-sheet0.png",
		"images/cave-sheet0.png",
		"images/cave-sheet1.png",
		"images/cave2_mirror-sheet0.png",
		"images/cave_mirror-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}